name: Feedback
description: Give us Feedback
title: "[Feedback]: "
labels: ["enhancement", "idea"]
projects: []
assignees:
  - zischler
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to give us feedback!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feedback
    attributes:
      label: Feedback / Idea
      description: Do you have any feedback for improving the Swiss Esports Hub or an idea for future features?
      placeholder: What is your idea?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Data Policy
      description: By submitting this issue, you agree to our [privacy policy](https://sesf.ch/privacy-policy/). 
      options:
        - label: I agree to the privacy policy of SESF
          required: true
