name: Idea
description: You have a feature request?
title: "[Idea]: "
labels: ["idea"]
projects: []
assignees:
  - zischler
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to send us your idea!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feedback
    attributes:
      label: Idea
      description: Do you have an idea for a possible feature?
      placeholder: What is your idea?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Data Policy
      description: By submitting this issue, you agree to our [privacy policy](https://sesf.ch/privacy-policy/). 
      options:
        - label: I agree to the privacy policy of SESF
          required: true
